#pragma once
enum {
    Ostainedglassgrid = 1053145,
    QUANTIZE_SPLINE_GROUP = 1000,
    QUANTIZE_SPLINE_ORDER = 1002,
    QUANTIZE_SPLINE_ORDER_XYZ = 1,
    QUANTIZE_SPLINE_ORDER_XZY = 2,
    QUANTIZE_SPLINE_ORDER_YXZ = 3,
    QUANTIZE_SPLINE_ORDER_YZX = 4,
    QUANTIZE_SPLINE_ORDER_ZYX = 5,
    QUANTIZE_SPLINE_ORDER_ZXY = 6,
};
